package engine

import (
	"github.com/mumax/3/cuda"
	"github.com/mumax/3/data"
	"github.com/mumax/3/mag"
)

var (
	JOersted = NewExcitation("J_oersted", "A/m2", "Current density used to calculate the Oersted field")
	IOersted = NewScalarExcitation("I_oersted", "", "Time-dependent multiplier for the Oersted field")
	BOersted = NewVectorField("B_oersted", "T", "Oersted field generated by J_oersted", setOerstedField)

	EnableOersted bool
	oerstedBase   *data.Slice
	oerstedConv   *cuda.OerstedConvolution

	lastJOerstedRevision uint64
	lastOerstedMeshSize  [3]int
	lastOerstedMeshPBC   [3]int
	lastOerstedCellSize  [3]float64
)

func init() {
	DeclVar("EnableOersted", &EnableOersted, "Enable the Oersted-field contribution to B_eff")
	IOersted.Set(1)
}

func setOerstedField(dst *data.Slice) {
	cuda.Zero(dst)
	if JOersted.isZero() {
		return
	}
	amplitude := float32(IOersted.Average())
	if amplitude == 0 {
		return
	}
	ensureOerstedBase()
	cuda.Madd2(dst, dst, oerstedBase, 1, amplitude)
}

func AddOerstedField(dst *data.Slice) {
	if !EnableOersted || JOersted.isZero() {
		return
	}
	amplitude := float32(IOersted.Average())
	if amplitude == 0 {
		return
	}
	ensureOerstedBase()
	cuda.Madd2(dst, dst, oerstedBase, 1, amplitude)
}

func ensureOerstedBase() {
	size, pbc, cell := Mesh().Size(), Mesh().PBC(), Mesh().CellSize()
	if oerstedBase != nil && oerstedConv != nil && size == lastOerstedMeshSize &&
		pbc == lastOerstedMeshPBC && cell == lastOerstedCellSize &&
		JOersted.Revision() == lastJOerstedRevision {
		return
	}
	recomputeOerstedBase(size, pbc, cell)
}

func recomputeOerstedBase(size, pbc [3]int, cell [3]float64) {
	if oerstedConv == nil || size != lastOerstedMeshSize || pbc != lastOerstedMeshPBC || cell != lastOerstedCellSize {
		if oerstedConv != nil {
			oerstedConv.Free()
		}
		kernel := mag.OerstedKernel(size, cell, pbc)
		oerstedConv = cuda.NewOersted(size, kernel)
		for _, component := range kernel {
			component.Free()
		}
	}
	if oerstedBase == nil || oerstedBase.Size() != size {
		if oerstedBase != nil {
			oerstedBase.Free()
		}
		oerstedBase = cuda.NewSlice(3, size)
	}
	current, recycle := JOersted.Slice()
	if recycle {
		defer cuda.Recycle(current)
	}
	oerstedConv.Exec(oerstedBase, current, geometry.Gpu())
	lastJOerstedRevision = JOersted.Revision()
	lastOerstedMeshSize, lastOerstedMeshPBC, lastOerstedCellSize = size, pbc, cell
}

func FreeOersted() {
	if oerstedConv != nil {
		oerstedConv.Free()
		oerstedConv = nil
	}
	if oerstedBase != nil {
		oerstedBase.Free()
		oerstedBase = nil
	}
	lastJOerstedRevision = 0
	lastOerstedMeshSize = [3]int{}
	lastOerstedMeshPBC = [3]int{}
	lastOerstedCellSize = [3]float64{}
}
