//go:build ignore
// +build ignore

// This program generates Go wrappers for cuda sources.
// The cuda file should contain exactly one __global__ void.

package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"regexp"
	"strconv"
	"strings"
	"text/scanner"
	"text/template"

	"github.com/mumax/3/util"
)

func main() {
	flag.Parse()
	for _, fname := range flag.Args() {
		cuda2go(fname)
	}
}

// generate cuda wrapper for file.
func cuda2go(fname string) {
	// open cuda file
	f, err := os.Open(fname)
	util.PanicErr(err)
	defer f.Close()

	// read tokens
	var token []string
	var s scanner.Scanner
	s.Init(f)
	tok := s.Scan()
	for tok != scanner.EOF {
		if !filter(s.TokenText()) {
			token = append(token, s.TokenText())
		}
		tok = s.Scan()
	}

	// find function name and arguments
	funcname := ""
	argstart, argstop := -1, -1
	for i := 0; i < len(token); i++ {
		if token[i] == "__global__" {
			funcname = token[i+2]
			argstart = i + 4
		}
		if argstart > 0 && token[i] == ")" {
			argstop = i + 1
			break
		}
	}
	argl := token[argstart:argstop]

	// isolate individual arguments
	var args [][]string
	start := 0
	for i, a := range argl {
		if a == "," || a == ")" {
			args = append(args, argl[start:i])
			start = i + 1
		}
	}

	// separate arg names/types and make pointers Go-style
	argn := make([]string, len(args))
	argt := make([]string, len(args))
	for i := range args {
		if args[i][1] == "*" {
			args[i] = []string{args[i][0] + "*", args[i][2]}
		}
		argt[i] = typemap(args[i][0])
		argn[i] = args[i][1]
	}
	wrapgen(fname, funcname, argt, argn)
}

// translate C type to Go type.
func typemap(ctype string) string {
	if gotype, ok := tm[ctype]; ok {
		return gotype
	}
	panic(fmt.Errorf("unsupported cuda type: %v", ctype))
}

var tm = map[string]string{"float*": "unsafe.Pointer", "float": "float32", "int": "int", "uint8_t*": "unsafe.Pointer", "uint8_t": "byte"}

// template data
type Kernel struct {
	Name      string
	GoName    string
	CamelName string
	ArgT      []string
	ArgN      []string
	GoArgN    []string
	PTX       map[int]string
}

var ls []string

// generate wrapper code from template
func wrapgen(filename, funcname string, argt, argn []string) {
	goArgN := make([]string, len(argn))
	for i, name := range argn {
		goArgN[i] = goStyleName(name)
	}
	kernel := &Kernel{
		Name:      funcname,
		GoName:    goStyleName(funcname),
		CamelName: lowerCamelName(funcname),
		ArgT:      argt,
		ArgN:      argn,
		GoArgN:    goArgN,
		PTX:       make(map[int]string),
	}

	// find corresponding .PTX files
	if ls == nil {
		dir, errd := os.Open(".")
		defer dir.Close()
		util.PanicErr(errd)
		var errls error
		ls, errls = dir.Readdirnames(-1)
		util.PanicErr(errls)
	}

	basename := util.NoExt(filename)
	for _, f := range ls {
		match, e := regexp.MatchString(`^`+basename+`_[0-9]+\.ptx`, f)
		util.PanicErr(e)
		if match {
			loc := regexp.MustCompile(`_[0-9]+\.ptx`).FindStringIndex(f) // Start and end indices of "_CC.ptx"
			cc, ei := strconv.Atoi(f[loc[0]+1 : loc[1]-len(".ptx")])
			util.PanicErr(ei)
			fmt.Println(basename, cc)
			kernel.PTX[cc] = filterptx(f)
		}
	}

	if len(kernel.PTX) == 0 {
		log.Fatal("no PTX files for ", filename)
	}

	wrapfname := basename + "_wrapper.go"
	wrapout, err := os.OpenFile(wrapfname, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
	util.PanicErr(err)
	defer wrapout.Close()
	util.PanicErr(templ.Execute(wrapout, kernel))
}

func goStyleName(name string) string {
	if name == "" {
		return name
	}

	parts := strings.Split(name, "_")
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return result.String()
}

func lowerCamelName(name string) string {
	styled := goStyleName(name)
	if styled == "" {
		return styled
	}
	return strings.ToLower(styled[:1]) + styled[1:]
}

// wrapper code template text
const templText = `package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for {{.Name}} kernel
var {{.CamelName}}Code cu.Function

// Stores the arguments for {{.Name}} kernel invocation
type {{.CamelName}}ArgsT struct {
	{{range $i, $_ := .ArgN}}arg{{index $.GoArgN $i}} {{index $.ArgT $i}}
	{{end}}argptr [{{len .ArgN}}]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for {{.Name}} kernel invocation
var {{.CamelName}}Args {{.CamelName}}ArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	{{range $i, $t := .ArgN}}{{$.CamelName}}Args.argptr[{{$i}}] = unsafe.Pointer(&{{$.CamelName}}Args.arg{{index $.GoArgN $i}})
	{{end}}}

// Wrapper for {{.Name}} CUDA kernel, asynchronous.
func k{{.GoName}}Async({{range $i, $t := .ArgT}}{{index $.ArgN $i}} {{$t}}, {{end}}cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("{{.Name}}")
	}

	{{.CamelName}}Args.Lock()
	defer {{.CamelName}}Args.Unlock()

	if {{.CamelName}}Code == 0 {
		{{.CamelName}}Code = fatbinLoad({{.CamelName}}Map, "{{.Name}}")
	}

	{{range $i, $t := .ArgN}}{{$.CamelName}}Args.arg{{index $.GoArgN $i}} = {{.}}
	{{end}}
	args := {{.CamelName}}Args.argptr[:]
	cu.LaunchKernel({{.CamelName}}Code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("{{.Name}}")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_{{.Name}}_async({{range $i, $t := .ArgT}}{{index $.ArgN $i}} {{$t}}, {{end}}cfg *config) {
	k{{.GoName}}Async({{range $i, $t := .ArgN}}{{.}}, {{end}}cfg)
}

// maps compute capability on PTX code for {{.Name}} kernel.
var {{.CamelName}}Map = map[int]string{
	0: "",{{range $k, $v := .PTX}}
	{{$k}}: {{$.CamelName}}Ptx{{$k}},{{end}}
}

// Backward-compatible map name used by the original fatbin registration.
var {{.Name}}_map = {{.CamelName}}Map

// {{.Name}} PTX code for various compute capabilities.
const (
	{{range $k, $v := .PTX}}{{$.CamelName}}Ptx{{$k}} = {{$v}}
	{{end}})
`

// wrapper code template
var templ = template.Must(template.New("wrap").Parse(templText))

// should token be filtered out of stream?
func filter(token string) bool {
	switch token {
	case "__restrict__":
		return true
	}
	return false
}

// Filter comments and ".file" entries from ptx code.
// They spoil the git history.
func filterptx(fname string) string {
	f, err := os.Open(fname)
	util.PanicErr(err)
	defer f.Close()
	in := bufio.NewReader(f)
	var out bytes.Buffer
	out.Write(([]byte)("`"))
	line, err := in.ReadBytes('\n')
	for err != io.EOF {
		util.PanicErr(err)
		if !bytes.HasPrefix(line, []byte("//")) && !bytes.HasPrefix(line, []byte("	.file")) {
			out.Write(line)
		}
		line, err = in.ReadBytes('\n')
	}
	out.Write(([]byte)("`"))
	return out.String()
}
