package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for madd4 kernel
var madd4Code cu.Function

// Stores the arguments for madd4 kernel invocation
type madd4ArgsT struct {
	argDst  unsafe.Pointer
	argSrc1 unsafe.Pointer
	argFac1 float32
	argSrc2 unsafe.Pointer
	argFac2 float32
	argSrc3 unsafe.Pointer
	argFac3 float32
	argSrc4 unsafe.Pointer
	argFac4 float32
	argN    int
	argptr  [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd4 kernel invocation
var madd4Args madd4ArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	madd4Args.argptr[0] = unsafe.Pointer(&madd4Args.argDst)
	madd4Args.argptr[1] = unsafe.Pointer(&madd4Args.argSrc1)
	madd4Args.argptr[2] = unsafe.Pointer(&madd4Args.argFac1)
	madd4Args.argptr[3] = unsafe.Pointer(&madd4Args.argSrc2)
	madd4Args.argptr[4] = unsafe.Pointer(&madd4Args.argFac2)
	madd4Args.argptr[5] = unsafe.Pointer(&madd4Args.argSrc3)
	madd4Args.argptr[6] = unsafe.Pointer(&madd4Args.argFac3)
	madd4Args.argptr[7] = unsafe.Pointer(&madd4Args.argSrc4)
	madd4Args.argptr[8] = unsafe.Pointer(&madd4Args.argFac4)
	madd4Args.argptr[9] = unsafe.Pointer(&madd4Args.argN)
}

// Wrapper for madd4 CUDA kernel, asynchronous.
func kMadd4Async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, src4 unsafe.Pointer, fac4 float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("madd4")
	}

	madd4Args.Lock()
	defer madd4Args.Unlock()

	if madd4Code == 0 {
		madd4Code = fatbinLoad(madd4Map, "madd4")
	}

	madd4Args.argDst = dst
	madd4Args.argSrc1 = src1
	madd4Args.argFac1 = fac1
	madd4Args.argSrc2 = src2
	madd4Args.argFac2 = fac2
	madd4Args.argSrc3 = src3
	madd4Args.argFac3 = fac3
	madd4Args.argSrc4 = src4
	madd4Args.argFac4 = fac4
	madd4Args.argN = N

	args := madd4Args.argptr[:]
	cu.LaunchKernel(madd4Code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("madd4")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_madd4_async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, src4 unsafe.Pointer, fac4 float32, N int, cfg *config) {
	kMadd4Async(dst, src1, fac1, src2, fac2, src3, fac3, src4, fac4, N, cfg)
}

// maps compute capability on PTX code for madd4 kernel.
var madd4Map = map[int]string{
	0:  "",
	50: madd4Ptx50,
	52: madd4Ptx52,
	53: madd4Ptx53,
	60: madd4Ptx60,
	61: madd4Ptx61,
	62: madd4Ptx62,
	70: madd4Ptx70,
	72: madd4Ptx72,
	75: madd4Ptx75,
	80: madd4Ptx80,
	86: madd4Ptx86,
	87: madd4Ptx87,
	89: madd4Ptx89,
	90: madd4Ptx90,
}

// Backward-compatible map name used by the original fatbin registration.
var madd4_map = madd4Map

// madd4 PTX code for various compute capabilities.
const (
	madd4Ptx50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx72 = `
.version 8.4
.target sm_72
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx75 = `
.version 8.4
.target sm_75
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx80 = `
.version 8.4
.target sm_80
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx86 = `
.version 8.4
.target sm_86
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx87 = `
.version 8.4
.target sm_87
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx89 = `
.version 8.4
.target sm_89
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
	madd4Ptx90 = `
.version 8.4
.target sm_90
.address_size 64

	// .globl	madd4

.visible .entry madd4(
	.param .u64 madd4_param_0,
	.param .u64 madd4_param_1,
	.param .f32 madd4_param_2,
	.param .u64 madd4_param_3,
	.param .f32 madd4_param_4,
	.param .u64 madd4_param_5,
	.param .f32 madd4_param_6,
	.param .u64 madd4_param_7,
	.param .f32 madd4_param_8,
	.param .u32 madd4_param_9
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<17>;


	ld.param.u64 	%rd1, [madd4_param_0];
	ld.param.u64 	%rd2, [madd4_param_1];
	ld.param.f32 	%f1, [madd4_param_2];
	ld.param.u64 	%rd3, [madd4_param_3];
	ld.param.f32 	%f2, [madd4_param_4];
	ld.param.u64 	%rd4, [madd4_param_5];
	ld.param.f32 	%f3, [madd4_param_6];
	ld.param.u64 	%rd5, [madd4_param_7];
	ld.param.f32 	%f4, [madd4_param_8];
	ld.param.u32 	%r2, [madd4_param_9];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd6, %rd2;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f5, [%rd8];
	cvta.to.global.u64 	%rd9, %rd3;
	add.s64 	%rd10, %rd9, %rd7;
	ld.global.nc.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f2;
	fma.rn.f32 	%f8, %f5, %f1, %f7;
	cvta.to.global.u64 	%rd11, %rd4;
	add.s64 	%rd12, %rd11, %rd7;
	ld.global.nc.f32 	%f9, [%rd12];
	fma.rn.f32 	%f10, %f9, %f3, %f8;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.nc.f32 	%f11, [%rd14];
	fma.rn.f32 	%f12, %f11, %f4, %f10;
	cvta.to.global.u64 	%rd15, %rd1;
	add.s64 	%rd16, %rd15, %rd7;
	st.global.f32 	[%rd16], %f12;

$L__BB0_2:
	ret;

}

`
)
