package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for regionadds kernel
var regionaddsCode cu.Function

// Stores the arguments for regionadds kernel invocation
type regionaddsArgsT struct {
	argDst     unsafe.Pointer
	argLUT     unsafe.Pointer
	argRegions unsafe.Pointer
	argN       int
	argptr     [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for regionadds kernel invocation
var regionaddsArgs regionaddsArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	regionaddsArgs.argptr[0] = unsafe.Pointer(&regionaddsArgs.argDst)
	regionaddsArgs.argptr[1] = unsafe.Pointer(&regionaddsArgs.argLUT)
	regionaddsArgs.argptr[2] = unsafe.Pointer(&regionaddsArgs.argRegions)
	regionaddsArgs.argptr[3] = unsafe.Pointer(&regionaddsArgs.argN)
}

// Wrapper for regionadds CUDA kernel, asynchronous.
func kRegionaddsAsync(dst unsafe.Pointer, LUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("regionadds")
	}

	regionaddsArgs.Lock()
	defer regionaddsArgs.Unlock()

	if regionaddsCode == 0 {
		regionaddsCode = fatbinLoad(regionaddsMap, "regionadds")
	}

	regionaddsArgs.argDst = dst
	regionaddsArgs.argLUT = LUT
	regionaddsArgs.argRegions = regions
	regionaddsArgs.argN = N

	args := regionaddsArgs.argptr[:]
	cu.LaunchKernel(regionaddsCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("regionadds")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_regionadds_async(dst unsafe.Pointer, LUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	kRegionaddsAsync(dst, LUT, regions, N, cfg)
}

// maps compute capability on PTX code for regionadds kernel.
var regionaddsMap = map[int]string{
	0:  "",
	50: regionaddsPtx50,
	52: regionaddsPtx52,
	53: regionaddsPtx53,
	60: regionaddsPtx60,
	61: regionaddsPtx61,
	62: regionaddsPtx62,
	70: regionaddsPtx70,
	72: regionaddsPtx72,
	75: regionaddsPtx75,
	80: regionaddsPtx80,
	86: regionaddsPtx86,
	87: regionaddsPtx87,
	89: regionaddsPtx89,
	90: regionaddsPtx90,
}

// Backward-compatible map name used by the original fatbin registration.
var regionadds_map = regionaddsMap

// regionadds PTX code for various compute capabilities.
const (
	regionaddsPtx50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx72 = `
.version 8.4
.target sm_72
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx75 = `
.version 8.4
.target sm_75
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx80 = `
.version 8.4
.target sm_80
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx86 = `
.version 8.4
.target sm_86
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx87 = `
.version 8.4
.target sm_87
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx89 = `
.version 8.4
.target sm_89
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
	regionaddsPtx90 = `
.version 8.4
.target sm_90
.address_size 64

	// .globl	regionadds

.visible .entry regionadds(
	.param .u64 regionadds_param_0,
	.param .u64 regionadds_param_1,
	.param .u64 regionadds_param_2,
	.param .u32 regionadds_param_3
)
{
	.reg .pred 	%p<2>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd1, [regionadds_param_0];
	ld.param.u64 	%rd2, [regionadds_param_1];
	ld.param.u64 	%rd3, [regionadds_param_2];
	ld.param.u32 	%r2, [regionadds_param_3];
	mov.u32 	%r3, %ctaid.y;
	mov.u32 	%r4, %nctaid.x;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd5, %r1;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd2;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r1, 4;
	add.s64 	%rd12, %rd10, %rd11;
	ld.global.f32 	%f1, [%rd12];
	ld.global.nc.f32 	%f2, [%rd9];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd12], %f3;

$L__BB0_2:
	ret;

}

`
)
