package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for addAFMexchange kernel
var addAFMexchange_code cu.Function

// Stores the arguments for addAFMexchange kernel invocation
type addAFMexchange_args_t struct{
	 arg_Bx unsafe.Pointer
	 arg_By unsafe.Pointer
	 arg_Bz unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_AFMex float32
	 arg_AFMR1 int
	 arg_AFMR2 int
	 arg_regions unsafe.Pointer
	 arg_wx float32
	 arg_wy float32
	 arg_wz float32
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_PBC uint16
	 argptr [17]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addAFMexchange kernel invocation
var addAFMexchange_args addAFMexchange_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 addAFMexchange_args.argptr[0] = unsafe.Pointer(&addAFMexchange_args.arg_Bx)
	 addAFMexchange_args.argptr[1] = unsafe.Pointer(&addAFMexchange_args.arg_By)
	 addAFMexchange_args.argptr[2] = unsafe.Pointer(&addAFMexchange_args.arg_Bz)
	 addAFMexchange_args.argptr[3] = unsafe.Pointer(&addAFMexchange_args.arg_mx)
	 addAFMexchange_args.argptr[4] = unsafe.Pointer(&addAFMexchange_args.arg_my)
	 addAFMexchange_args.argptr[5] = unsafe.Pointer(&addAFMexchange_args.arg_mz)
	 addAFMexchange_args.argptr[6] = unsafe.Pointer(&addAFMexchange_args.arg_AFMex)
	 addAFMexchange_args.argptr[7] = unsafe.Pointer(&addAFMexchange_args.arg_AFMR1)
	 addAFMexchange_args.argptr[8] = unsafe.Pointer(&addAFMexchange_args.arg_AFMR2)
	 addAFMexchange_args.argptr[9] = unsafe.Pointer(&addAFMexchange_args.arg_regions)
	 addAFMexchange_args.argptr[10] = unsafe.Pointer(&addAFMexchange_args.arg_wx)
	 addAFMexchange_args.argptr[11] = unsafe.Pointer(&addAFMexchange_args.arg_wy)
	 addAFMexchange_args.argptr[12] = unsafe.Pointer(&addAFMexchange_args.arg_wz)
	 addAFMexchange_args.argptr[13] = unsafe.Pointer(&addAFMexchange_args.arg_Nx)
	 addAFMexchange_args.argptr[14] = unsafe.Pointer(&addAFMexchange_args.arg_Ny)
	 addAFMexchange_args.argptr[15] = unsafe.Pointer(&addAFMexchange_args.arg_Nz)
	 addAFMexchange_args.argptr[16] = unsafe.Pointer(&addAFMexchange_args.arg_PBC)
	 }

// Wrapper for addAFMexchange CUDA kernel, asynchronous.
func k_addAFMexchange_async ( Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, AFMex float32, AFMR1 int, AFMR2 int, regions unsafe.Pointer, wx float32, wy float32, wz float32, Nx int, Ny int, Nz int, PBC uint16,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("addAFMexchange")
	}

	addAFMexchange_args.Lock()
	defer addAFMexchange_args.Unlock()

	if addAFMexchange_code == 0{
		addAFMexchange_code = fatbinLoad(addAFMexchange_map, "addAFMexchange")
	}

	 addAFMexchange_args.arg_Bx = Bx
	 addAFMexchange_args.arg_By = By
	 addAFMexchange_args.arg_Bz = Bz
	 addAFMexchange_args.arg_mx = mx
	 addAFMexchange_args.arg_my = my
	 addAFMexchange_args.arg_mz = mz
	 addAFMexchange_args.arg_AFMex = AFMex
	 addAFMexchange_args.arg_AFMR1 = AFMR1
	 addAFMexchange_args.arg_AFMR2 = AFMR2
	 addAFMexchange_args.arg_regions = regions
	 addAFMexchange_args.arg_wx = wx
	 addAFMexchange_args.arg_wy = wy
	 addAFMexchange_args.arg_wz = wz
	 addAFMexchange_args.arg_Nx = Nx
	 addAFMexchange_args.arg_Ny = Ny
	 addAFMexchange_args.arg_Nz = Nz
	 addAFMexchange_args.arg_PBC = PBC
	

	args := addAFMexchange_args.argptr[:]
	cu.LaunchKernel(addAFMexchange_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("addAFMexchange")
	}
}

// maps compute capability on PTX code for addAFMexchange kernel.
var addAFMexchange_map = map[int]string{ 0: "" ,
20: addAFMexchange_ptx_20 ,
30: addAFMexchange_ptx_30 ,
35: addAFMexchange_ptx_35 ,
50: addAFMexchange_ptx_50 ,
52: addAFMexchange_ptx_52 ,
53: addAFMexchange_ptx_53  }

// addAFMexchange PTX code for various compute capabilities.
const(
  addAFMexchange_ptx_20 = `
.version 4.3
.target sm_20
.address_size 64

	// .globl	addAFMexchange

.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<62>;
	.reg .b64 	%rd<39>;


	ld.param.u64 	%rd2, [addAFMexchange_param_0];
	ld.param.u64 	%rd3, [addAFMexchange_param_1];
	ld.param.u64 	%rd4, [addAFMexchange_param_2];
	ld.param.u64 	%rd5, [addAFMexchange_param_3];
	ld.param.u64 	%rd6, [addAFMexchange_param_4];
	ld.param.u64 	%rd7, [addAFMexchange_param_5];
	ld.param.f32 	%f19, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_7;

	cvta.to.global.u64 	%rd8, %rd7;
	cvta.to.global.u64 	%rd9, %rd6;
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd2;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd12, %r19, 4;
	add.s64 	%rd13, %rd10, %rd12;
	add.s64 	%rd14, %rd9, %rd12;
	add.s64 	%rd15, %rd8, %rd12;
	ld.global.f32 	%f1, [%rd15];
	ld.global.f32 	%f2, [%rd13];
	ld.global.f32 	%f3, [%rd14];
	add.s64 	%rd16, %rd11, %rd12;
	ld.global.f32 	%f44, [%rd16];
	cvta.to.global.u64 	%rd17, %rd3;
	add.s64 	%rd18, %rd17, %rd12;
	ld.global.f32 	%f45, [%rd18];
	cvta.to.global.u64 	%rd19, %rd4;
	add.s64 	%rd1, %rd19, %rd12;
	ld.global.f32 	%f46, [%rd1];
	setp.eq.f32	%p6, %f19, 0f00000000;
	@%p6 bra 	BB0_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB0_4;

	mad.lo.s32 	%r28, %r7, %r5, %r2;
	mad.lo.s32 	%r33, %r28, %r6, %r1;
	mul.wide.s32 	%rd21, %r33, 4;
	add.s64 	%rd22, %rd10, %rd21;
	add.s64 	%rd24, %rd9, %rd21;
	add.s64 	%rd26, %rd8, %rd21;
	ld.global.f32 	%f20, [%rd22];
	ld.global.f32 	%f21, [%rd24];
	ld.global.f32 	%f22, [%rd26];
	mul.f32 	%f23, %f21, %f21;
	fma.rn.f32 	%f24, %f20, %f20, %f23;
	fma.rn.f32 	%f25, %f22, %f22, %f24;
	setp.eq.f32	%p8, %f25, 0f00000000;
	selp.f32	%f26, %f1, %f22, %p8;
	selp.f32	%f27, %f3, %f21, %p8;
	selp.f32	%f28, %f2, %f20, %p8;
	sub.f32 	%f29, %f28, %f2;
	sub.f32 	%f30, %f27, %f3;
	sub.f32 	%f31, %f26, %f1;
	fma.rn.f32 	%f44, %f29, %f19, %f44;
	fma.rn.f32 	%f45, %f30, %f19, %f45;
	fma.rn.f32 	%f46, %f31, %f19, %f46;

BB0_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB0_6;

	mad.lo.s32 	%r42, %r7, %r4, %r2;
	mad.lo.s32 	%r47, %r42, %r6, %r1;
	mul.wide.s32 	%rd28, %r47, 4;
	add.s64 	%rd29, %rd10, %rd28;
	add.s64 	%rd31, %rd9, %rd28;
	add.s64 	%rd33, %rd8, %rd28;
	ld.global.f32 	%f32, [%rd29];
	ld.global.f32 	%f33, [%rd31];
	ld.global.f32 	%f34, [%rd33];
	mul.f32 	%f35, %f33, %f33;
	fma.rn.f32 	%f36, %f32, %f32, %f35;
	fma.rn.f32 	%f37, %f34, %f34, %f36;
	setp.eq.f32	%p10, %f37, 0f00000000;
	selp.f32	%f38, %f1, %f34, %p10;
	selp.f32	%f39, %f3, %f33, %p10;
	selp.f32	%f40, %f2, %f32, %p10;
	sub.f32 	%f41, %f40, %f2;
	sub.f32 	%f42, %f39, %f3;
	sub.f32 	%f43, %f38, %f1;
	fma.rn.f32 	%f44, %f41, %f19, %f44;
	fma.rn.f32 	%f45, %f42, %f19, %f45;
	fma.rn.f32 	%f46, %f43, %f19, %f46;

BB0_6:
	st.global.f32 	[%rd16], %f44;
	st.global.f32 	[%rd18], %f45;
	st.global.f32 	[%rd1], %f46;

BB0_7:
	ret;
}


`
   addAFMexchange_ptx_30 = `
.version 4.3
.target sm_30
.address_size 64

	// .globl	addAFMexchange

.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<62>;
	.reg .b64 	%rd<39>;


	ld.param.u64 	%rd2, [addAFMexchange_param_0];
	ld.param.u64 	%rd3, [addAFMexchange_param_1];
	ld.param.u64 	%rd4, [addAFMexchange_param_2];
	ld.param.u64 	%rd5, [addAFMexchange_param_3];
	ld.param.u64 	%rd6, [addAFMexchange_param_4];
	ld.param.u64 	%rd7, [addAFMexchange_param_5];
	ld.param.f32 	%f19, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_7;

	cvta.to.global.u64 	%rd8, %rd7;
	cvta.to.global.u64 	%rd9, %rd6;
	cvta.to.global.u64 	%rd10, %rd5;
	cvta.to.global.u64 	%rd11, %rd2;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd12, %r19, 4;
	add.s64 	%rd13, %rd10, %rd12;
	add.s64 	%rd14, %rd9, %rd12;
	add.s64 	%rd15, %rd8, %rd12;
	ld.global.f32 	%f1, [%rd15];
	ld.global.f32 	%f2, [%rd13];
	ld.global.f32 	%f3, [%rd14];
	add.s64 	%rd16, %rd11, %rd12;
	ld.global.f32 	%f44, [%rd16];
	cvta.to.global.u64 	%rd17, %rd3;
	add.s64 	%rd18, %rd17, %rd12;
	ld.global.f32 	%f45, [%rd18];
	cvta.to.global.u64 	%rd19, %rd4;
	add.s64 	%rd1, %rd19, %rd12;
	ld.global.f32 	%f46, [%rd1];
	setp.eq.f32	%p6, %f19, 0f00000000;
	@%p6 bra 	BB0_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB0_4;

	mad.lo.s32 	%r28, %r7, %r5, %r2;
	mad.lo.s32 	%r33, %r28, %r6, %r1;
	mul.wide.s32 	%rd21, %r33, 4;
	add.s64 	%rd22, %rd10, %rd21;
	add.s64 	%rd24, %rd9, %rd21;
	add.s64 	%rd26, %rd8, %rd21;
	ld.global.f32 	%f20, [%rd22];
	ld.global.f32 	%f21, [%rd24];
	ld.global.f32 	%f22, [%rd26];
	mul.f32 	%f23, %f21, %f21;
	fma.rn.f32 	%f24, %f20, %f20, %f23;
	fma.rn.f32 	%f25, %f22, %f22, %f24;
	setp.eq.f32	%p8, %f25, 0f00000000;
	selp.f32	%f26, %f1, %f22, %p8;
	selp.f32	%f27, %f3, %f21, %p8;
	selp.f32	%f28, %f2, %f20, %p8;
	sub.f32 	%f29, %f28, %f2;
	sub.f32 	%f30, %f27, %f3;
	sub.f32 	%f31, %f26, %f1;
	fma.rn.f32 	%f44, %f29, %f19, %f44;
	fma.rn.f32 	%f45, %f30, %f19, %f45;
	fma.rn.f32 	%f46, %f31, %f19, %f46;

BB0_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB0_6;

	mad.lo.s32 	%r42, %r7, %r4, %r2;
	mad.lo.s32 	%r47, %r42, %r6, %r1;
	mul.wide.s32 	%rd28, %r47, 4;
	add.s64 	%rd29, %rd10, %rd28;
	add.s64 	%rd31, %rd9, %rd28;
	add.s64 	%rd33, %rd8, %rd28;
	ld.global.f32 	%f32, [%rd29];
	ld.global.f32 	%f33, [%rd31];
	ld.global.f32 	%f34, [%rd33];
	mul.f32 	%f35, %f33, %f33;
	fma.rn.f32 	%f36, %f32, %f32, %f35;
	fma.rn.f32 	%f37, %f34, %f34, %f36;
	setp.eq.f32	%p10, %f37, 0f00000000;
	selp.f32	%f38, %f1, %f34, %p10;
	selp.f32	%f39, %f3, %f33, %p10;
	selp.f32	%f40, %f2, %f32, %p10;
	sub.f32 	%f41, %f40, %f2;
	sub.f32 	%f42, %f39, %f3;
	sub.f32 	%f43, %f38, %f1;
	fma.rn.f32 	%f44, %f41, %f19, %f44;
	fma.rn.f32 	%f45, %f42, %f19, %f45;
	fma.rn.f32 	%f46, %f43, %f19, %f46;

BB0_6:
	st.global.f32 	[%rd16], %f44;
	st.global.f32 	[%rd18], %f45;
	st.global.f32 	[%rd1], %f46;

BB0_7:
	ret;
}


`
   addAFMexchange_ptx_35 = `
.version 4.3
.target sm_35
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	addAFMexchange
.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd7, [addAFMexchange_param_0];
	ld.param.u64 	%rd8, [addAFMexchange_param_1];
	ld.param.u64 	%rd9, [addAFMexchange_param_2];
	ld.param.u64 	%rd10, [addAFMexchange_param_3];
	ld.param.u64 	%rd11, [addAFMexchange_param_4];
	ld.param.u64 	%rd12, [addAFMexchange_param_5];
	ld.param.f32 	%f22, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB6_7;

	cvta.to.global.u64 	%rd13, %rd7;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd14, %r19, 4;
	add.s64 	%rd15, %rd3, %rd14;
	add.s64 	%rd16, %rd2, %rd14;
	add.s64 	%rd17, %rd1, %rd14;
	ld.global.nc.f32 	%f1, [%rd15];
	ld.global.nc.f32 	%f2, [%rd16];
	ld.global.nc.f32 	%f3, [%rd17];
	add.s64 	%rd4, %rd13, %rd14;
	ld.global.f32 	%f47, [%rd4];
	cvta.to.global.u64 	%rd18, %rd8;
	add.s64 	%rd5, %rd18, %rd14;
	ld.global.f32 	%f48, [%rd5];
	cvta.to.global.u64 	%rd19, %rd9;
	add.s64 	%rd6, %rd19, %rd14;
	ld.global.f32 	%f49, [%rd6];
	setp.eq.f32	%p6, %f22, 0f00000000;
	@%p6 bra 	BB6_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB6_4;

	mad.lo.s32 	%r20, %r7, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r6, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd3, %rd20;
	add.s64 	%rd22, %rd2, %rd20;
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f23, [%rd21];
	ld.global.nc.f32 	%f24, [%rd22];
	ld.global.nc.f32 	%f25, [%rd23];
	mul.f32 	%f26, %f24, %f24;
	fma.rn.f32 	%f27, %f23, %f23, %f26;
	fma.rn.f32 	%f28, %f25, %f25, %f27;
	setp.eq.f32	%p8, %f28, 0f00000000;
	selp.f32	%f29, %f3, %f25, %p8;
	selp.f32	%f30, %f2, %f24, %p8;
	selp.f32	%f31, %f1, %f23, %p8;
	sub.f32 	%f32, %f31, %f1;
	sub.f32 	%f33, %f30, %f2;
	sub.f32 	%f34, %f29, %f3;
	fma.rn.f32 	%f47, %f32, %f22, %f47;
	fma.rn.f32 	%f48, %f33, %f22, %f48;
	fma.rn.f32 	%f49, %f34, %f22, %f49;

BB6_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB6_6;

	mad.lo.s32 	%r22, %r7, %r4, %r2;
	mad.lo.s32 	%r23, %r22, %r6, %r1;
	mul.wide.s32 	%rd24, %r23, 4;
	add.s64 	%rd25, %rd3, %rd24;
	add.s64 	%rd26, %rd2, %rd24;
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f35, [%rd25];
	ld.global.nc.f32 	%f36, [%rd26];
	ld.global.nc.f32 	%f37, [%rd27];
	mul.f32 	%f38, %f36, %f36;
	fma.rn.f32 	%f39, %f35, %f35, %f38;
	fma.rn.f32 	%f40, %f37, %f37, %f39;
	setp.eq.f32	%p10, %f40, 0f00000000;
	selp.f32	%f41, %f3, %f37, %p10;
	selp.f32	%f42, %f2, %f36, %p10;
	selp.f32	%f43, %f1, %f35, %p10;
	sub.f32 	%f44, %f43, %f1;
	sub.f32 	%f45, %f42, %f2;
	sub.f32 	%f46, %f41, %f3;
	fma.rn.f32 	%f47, %f44, %f22, %f47;
	fma.rn.f32 	%f48, %f45, %f22, %f48;
	fma.rn.f32 	%f49, %f46, %f22, %f49;

BB6_6:
	st.global.f32 	[%rd4], %f47;
	st.global.f32 	[%rd5], %f48;
	st.global.f32 	[%rd6], %f49;

BB6_7:
	ret;
}


`
   addAFMexchange_ptx_50 = `
.version 4.3
.target sm_50
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	addAFMexchange
.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd7, [addAFMexchange_param_0];
	ld.param.u64 	%rd8, [addAFMexchange_param_1];
	ld.param.u64 	%rd9, [addAFMexchange_param_2];
	ld.param.u64 	%rd10, [addAFMexchange_param_3];
	ld.param.u64 	%rd11, [addAFMexchange_param_4];
	ld.param.u64 	%rd12, [addAFMexchange_param_5];
	ld.param.f32 	%f22, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB6_7;

	cvta.to.global.u64 	%rd13, %rd7;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd14, %r19, 4;
	add.s64 	%rd15, %rd3, %rd14;
	add.s64 	%rd16, %rd2, %rd14;
	add.s64 	%rd17, %rd1, %rd14;
	ld.global.nc.f32 	%f1, [%rd15];
	ld.global.nc.f32 	%f2, [%rd16];
	ld.global.nc.f32 	%f3, [%rd17];
	add.s64 	%rd4, %rd13, %rd14;
	ld.global.f32 	%f47, [%rd4];
	cvta.to.global.u64 	%rd18, %rd8;
	add.s64 	%rd5, %rd18, %rd14;
	ld.global.f32 	%f48, [%rd5];
	cvta.to.global.u64 	%rd19, %rd9;
	add.s64 	%rd6, %rd19, %rd14;
	ld.global.f32 	%f49, [%rd6];
	setp.eq.f32	%p6, %f22, 0f00000000;
	@%p6 bra 	BB6_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB6_4;

	mad.lo.s32 	%r20, %r7, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r6, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd3, %rd20;
	add.s64 	%rd22, %rd2, %rd20;
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f23, [%rd21];
	ld.global.nc.f32 	%f24, [%rd22];
	ld.global.nc.f32 	%f25, [%rd23];
	mul.f32 	%f26, %f24, %f24;
	fma.rn.f32 	%f27, %f23, %f23, %f26;
	fma.rn.f32 	%f28, %f25, %f25, %f27;
	setp.eq.f32	%p8, %f28, 0f00000000;
	selp.f32	%f29, %f3, %f25, %p8;
	selp.f32	%f30, %f2, %f24, %p8;
	selp.f32	%f31, %f1, %f23, %p8;
	sub.f32 	%f32, %f31, %f1;
	sub.f32 	%f33, %f30, %f2;
	sub.f32 	%f34, %f29, %f3;
	fma.rn.f32 	%f47, %f32, %f22, %f47;
	fma.rn.f32 	%f48, %f33, %f22, %f48;
	fma.rn.f32 	%f49, %f34, %f22, %f49;

BB6_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB6_6;

	mad.lo.s32 	%r22, %r7, %r4, %r2;
	mad.lo.s32 	%r23, %r22, %r6, %r1;
	mul.wide.s32 	%rd24, %r23, 4;
	add.s64 	%rd25, %rd3, %rd24;
	add.s64 	%rd26, %rd2, %rd24;
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f35, [%rd25];
	ld.global.nc.f32 	%f36, [%rd26];
	ld.global.nc.f32 	%f37, [%rd27];
	mul.f32 	%f38, %f36, %f36;
	fma.rn.f32 	%f39, %f35, %f35, %f38;
	fma.rn.f32 	%f40, %f37, %f37, %f39;
	setp.eq.f32	%p10, %f40, 0f00000000;
	selp.f32	%f41, %f3, %f37, %p10;
	selp.f32	%f42, %f2, %f36, %p10;
	selp.f32	%f43, %f1, %f35, %p10;
	sub.f32 	%f44, %f43, %f1;
	sub.f32 	%f45, %f42, %f2;
	sub.f32 	%f46, %f41, %f3;
	fma.rn.f32 	%f47, %f44, %f22, %f47;
	fma.rn.f32 	%f48, %f45, %f22, %f48;
	fma.rn.f32 	%f49, %f46, %f22, %f49;

BB6_6:
	st.global.f32 	[%rd4], %f47;
	st.global.f32 	[%rd5], %f48;
	st.global.f32 	[%rd6], %f49;

BB6_7:
	ret;
}


`
   addAFMexchange_ptx_52 = `
.version 4.3
.target sm_52
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	addAFMexchange
.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd7, [addAFMexchange_param_0];
	ld.param.u64 	%rd8, [addAFMexchange_param_1];
	ld.param.u64 	%rd9, [addAFMexchange_param_2];
	ld.param.u64 	%rd10, [addAFMexchange_param_3];
	ld.param.u64 	%rd11, [addAFMexchange_param_4];
	ld.param.u64 	%rd12, [addAFMexchange_param_5];
	ld.param.f32 	%f22, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB6_7;

	cvta.to.global.u64 	%rd13, %rd7;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd14, %r19, 4;
	add.s64 	%rd15, %rd3, %rd14;
	add.s64 	%rd16, %rd2, %rd14;
	add.s64 	%rd17, %rd1, %rd14;
	ld.global.nc.f32 	%f1, [%rd15];
	ld.global.nc.f32 	%f2, [%rd16];
	ld.global.nc.f32 	%f3, [%rd17];
	add.s64 	%rd4, %rd13, %rd14;
	ld.global.f32 	%f47, [%rd4];
	cvta.to.global.u64 	%rd18, %rd8;
	add.s64 	%rd5, %rd18, %rd14;
	ld.global.f32 	%f48, [%rd5];
	cvta.to.global.u64 	%rd19, %rd9;
	add.s64 	%rd6, %rd19, %rd14;
	ld.global.f32 	%f49, [%rd6];
	setp.eq.f32	%p6, %f22, 0f00000000;
	@%p6 bra 	BB6_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB6_4;

	mad.lo.s32 	%r20, %r7, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r6, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd3, %rd20;
	add.s64 	%rd22, %rd2, %rd20;
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f23, [%rd21];
	ld.global.nc.f32 	%f24, [%rd22];
	ld.global.nc.f32 	%f25, [%rd23];
	mul.f32 	%f26, %f24, %f24;
	fma.rn.f32 	%f27, %f23, %f23, %f26;
	fma.rn.f32 	%f28, %f25, %f25, %f27;
	setp.eq.f32	%p8, %f28, 0f00000000;
	selp.f32	%f29, %f3, %f25, %p8;
	selp.f32	%f30, %f2, %f24, %p8;
	selp.f32	%f31, %f1, %f23, %p8;
	sub.f32 	%f32, %f31, %f1;
	sub.f32 	%f33, %f30, %f2;
	sub.f32 	%f34, %f29, %f3;
	fma.rn.f32 	%f47, %f32, %f22, %f47;
	fma.rn.f32 	%f48, %f33, %f22, %f48;
	fma.rn.f32 	%f49, %f34, %f22, %f49;

BB6_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB6_6;

	mad.lo.s32 	%r22, %r7, %r4, %r2;
	mad.lo.s32 	%r23, %r22, %r6, %r1;
	mul.wide.s32 	%rd24, %r23, 4;
	add.s64 	%rd25, %rd3, %rd24;
	add.s64 	%rd26, %rd2, %rd24;
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f35, [%rd25];
	ld.global.nc.f32 	%f36, [%rd26];
	ld.global.nc.f32 	%f37, [%rd27];
	mul.f32 	%f38, %f36, %f36;
	fma.rn.f32 	%f39, %f35, %f35, %f38;
	fma.rn.f32 	%f40, %f37, %f37, %f39;
	setp.eq.f32	%p10, %f40, 0f00000000;
	selp.f32	%f41, %f3, %f37, %p10;
	selp.f32	%f42, %f2, %f36, %p10;
	selp.f32	%f43, %f1, %f35, %p10;
	sub.f32 	%f44, %f43, %f1;
	sub.f32 	%f45, %f42, %f2;
	sub.f32 	%f46, %f41, %f3;
	fma.rn.f32 	%f47, %f44, %f22, %f47;
	fma.rn.f32 	%f48, %f45, %f22, %f48;
	fma.rn.f32 	%f49, %f46, %f22, %f49;

BB6_6:
	st.global.f32 	[%rd4], %f47;
	st.global.f32 	[%rd5], %f48;
	st.global.f32 	[%rd6], %f49;

BB6_7:
	ret;
}


`
   addAFMexchange_ptx_53 = `
.version 4.3
.target sm_53
.address_size 64

	// .weak	cudaMalloc

.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaFuncGetAttributes
.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaDeviceGetAttribute
.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaGetDevice
.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessor
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .weak	cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_3,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_param_4
)
{
	.reg .b32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

	// .globl	addAFMexchange
.visible .entry addAFMexchange(
	.param .u64 addAFMexchange_param_0,
	.param .u64 addAFMexchange_param_1,
	.param .u64 addAFMexchange_param_2,
	.param .u64 addAFMexchange_param_3,
	.param .u64 addAFMexchange_param_4,
	.param .u64 addAFMexchange_param_5,
	.param .f32 addAFMexchange_param_6,
	.param .u32 addAFMexchange_param_7,
	.param .u32 addAFMexchange_param_8,
	.param .u64 addAFMexchange_param_9,
	.param .f32 addAFMexchange_param_10,
	.param .f32 addAFMexchange_param_11,
	.param .f32 addAFMexchange_param_12,
	.param .u32 addAFMexchange_param_13,
	.param .u32 addAFMexchange_param_14,
	.param .u32 addAFMexchange_param_15,
	.param .u16 addAFMexchange_param_16
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<50>;
	.reg .b32 	%r<24>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd7, [addAFMexchange_param_0];
	ld.param.u64 	%rd8, [addAFMexchange_param_1];
	ld.param.u64 	%rd9, [addAFMexchange_param_2];
	ld.param.u64 	%rd10, [addAFMexchange_param_3];
	ld.param.u64 	%rd11, [addAFMexchange_param_4];
	ld.param.u64 	%rd12, [addAFMexchange_param_5];
	ld.param.f32 	%f22, [addAFMexchange_param_6];
	ld.param.u32 	%r4, [addAFMexchange_param_7];
	ld.param.u32 	%r5, [addAFMexchange_param_8];
	ld.param.u32 	%r6, [addAFMexchange_param_13];
	ld.param.u32 	%r7, [addAFMexchange_param_14];
	ld.param.u32 	%r8, [addAFMexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r9, %r10, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r12, %r13, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r15, %r16, %r17;
	setp.ge.s32	%p1, %r2, %r7;
	setp.ge.s32	%p2, %r1, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB6_7;

	cvta.to.global.u64 	%rd13, %rd7;
	mad.lo.s32 	%r18, %r3, %r7, %r2;
	mad.lo.s32 	%r19, %r18, %r6, %r1;
	mul.wide.s32 	%rd14, %r19, 4;
	add.s64 	%rd15, %rd3, %rd14;
	add.s64 	%rd16, %rd2, %rd14;
	add.s64 	%rd17, %rd1, %rd14;
	ld.global.nc.f32 	%f1, [%rd15];
	ld.global.nc.f32 	%f2, [%rd16];
	ld.global.nc.f32 	%f3, [%rd17];
	add.s64 	%rd4, %rd13, %rd14;
	ld.global.f32 	%f47, [%rd4];
	cvta.to.global.u64 	%rd18, %rd8;
	add.s64 	%rd5, %rd18, %rd14;
	ld.global.f32 	%f48, [%rd5];
	cvta.to.global.u64 	%rd19, %rd9;
	add.s64 	%rd6, %rd19, %rd14;
	ld.global.f32 	%f49, [%rd6];
	setp.eq.f32	%p6, %f22, 0f00000000;
	@%p6 bra 	BB6_6;

	setp.ne.s32	%p7, %r3, %r4;
	@%p7 bra 	BB6_4;

	mad.lo.s32 	%r20, %r7, %r5, %r2;
	mad.lo.s32 	%r21, %r20, %r6, %r1;
	mul.wide.s32 	%rd20, %r21, 4;
	add.s64 	%rd21, %rd3, %rd20;
	add.s64 	%rd22, %rd2, %rd20;
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f23, [%rd21];
	ld.global.nc.f32 	%f24, [%rd22];
	ld.global.nc.f32 	%f25, [%rd23];
	mul.f32 	%f26, %f24, %f24;
	fma.rn.f32 	%f27, %f23, %f23, %f26;
	fma.rn.f32 	%f28, %f25, %f25, %f27;
	setp.eq.f32	%p8, %f28, 0f00000000;
	selp.f32	%f29, %f3, %f25, %p8;
	selp.f32	%f30, %f2, %f24, %p8;
	selp.f32	%f31, %f1, %f23, %p8;
	sub.f32 	%f32, %f31, %f1;
	sub.f32 	%f33, %f30, %f2;
	sub.f32 	%f34, %f29, %f3;
	fma.rn.f32 	%f47, %f32, %f22, %f47;
	fma.rn.f32 	%f48, %f33, %f22, %f48;
	fma.rn.f32 	%f49, %f34, %f22, %f49;

BB6_4:
	setp.ne.s32	%p9, %r3, %r5;
	@%p9 bra 	BB6_6;

	mad.lo.s32 	%r22, %r7, %r4, %r2;
	mad.lo.s32 	%r23, %r22, %r6, %r1;
	mul.wide.s32 	%rd24, %r23, 4;
	add.s64 	%rd25, %rd3, %rd24;
	add.s64 	%rd26, %rd2, %rd24;
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f35, [%rd25];
	ld.global.nc.f32 	%f36, [%rd26];
	ld.global.nc.f32 	%f37, [%rd27];
	mul.f32 	%f38, %f36, %f36;
	fma.rn.f32 	%f39, %f35, %f35, %f38;
	fma.rn.f32 	%f40, %f37, %f37, %f39;
	setp.eq.f32	%p10, %f40, 0f00000000;
	selp.f32	%f41, %f3, %f37, %p10;
	selp.f32	%f42, %f2, %f36, %p10;
	selp.f32	%f43, %f1, %f35, %p10;
	sub.f32 	%f44, %f43, %f1;
	sub.f32 	%f45, %f42, %f2;
	sub.f32 	%f46, %f41, %f3;
	fma.rn.f32 	%f47, %f44, %f22, %f47;
	fma.rn.f32 	%f48, %f45, %f22, %f48;
	fma.rn.f32 	%f49, %f46, %f22, %f49;

BB6_6:
	st.global.f32 	[%rd4], %f47;
	st.global.f32 	[%rd5], %f48;
	st.global.f32 	[%rd6], %f49;

BB6_7:
	ret;
}


`
 )
