package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for shiftbytesy kernel
var shiftbytesyCode cu.Function

// Stores the arguments for shiftbytesy kernel invocation
type shiftbytesyArgsT struct {
	argDst   unsafe.Pointer
	argSrc   unsafe.Pointer
	argNx    int
	argNy    int
	argNz    int
	argShy   int
	argClamp byte
	argptr   [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shiftbytesy kernel invocation
var shiftbytesyArgs shiftbytesyArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	shiftbytesyArgs.argptr[0] = unsafe.Pointer(&shiftbytesyArgs.argDst)
	shiftbytesyArgs.argptr[1] = unsafe.Pointer(&shiftbytesyArgs.argSrc)
	shiftbytesyArgs.argptr[2] = unsafe.Pointer(&shiftbytesyArgs.argNx)
	shiftbytesyArgs.argptr[3] = unsafe.Pointer(&shiftbytesyArgs.argNy)
	shiftbytesyArgs.argptr[4] = unsafe.Pointer(&shiftbytesyArgs.argNz)
	shiftbytesyArgs.argptr[5] = unsafe.Pointer(&shiftbytesyArgs.argShy)
	shiftbytesyArgs.argptr[6] = unsafe.Pointer(&shiftbytesyArgs.argClamp)
}

// Wrapper for shiftbytesy CUDA kernel, asynchronous.
func kShiftbytesyAsync(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shy int, clamp byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("shiftbytesy")
	}

	shiftbytesyArgs.Lock()
	defer shiftbytesyArgs.Unlock()

	if shiftbytesyCode == 0 {
		shiftbytesyCode = fatbinLoad(shiftbytesyMap, "shiftbytesy")
	}

	shiftbytesyArgs.argDst = dst
	shiftbytesyArgs.argSrc = src
	shiftbytesyArgs.argNx = Nx
	shiftbytesyArgs.argNy = Ny
	shiftbytesyArgs.argNz = Nz
	shiftbytesyArgs.argShy = shy
	shiftbytesyArgs.argClamp = clamp

	args := shiftbytesyArgs.argptr[:]
	cu.LaunchKernel(shiftbytesyCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("shiftbytesy")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_shiftbytesy_async(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shy int, clamp byte, cfg *config) {
	kShiftbytesyAsync(dst, src, Nx, Ny, Nz, shy, clamp, cfg)
}

// maps compute capability on PTX code for shiftbytesy kernel.
var shiftbytesyMap = map[int]string{
	0:  "",
	50: shiftbytesyPtx50,
	52: shiftbytesyPtx52,
	53: shiftbytesyPtx53,
	60: shiftbytesyPtx60,
	61: shiftbytesyPtx61,
	62: shiftbytesyPtx62,
	70: shiftbytesyPtx70,
	72: shiftbytesyPtx72,
	75: shiftbytesyPtx75,
	80: shiftbytesyPtx80,
	86: shiftbytesyPtx86,
	87: shiftbytesyPtx87,
	89: shiftbytesyPtx89,
	90: shiftbytesyPtx90,
}

// Backward-compatible map name used by the original fatbin registration.
var shiftbytesy_map = shiftbytesyMap

// shiftbytesy PTX code for various compute capabilities.
const (
	shiftbytesyPtx50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx72 = `
.version 8.4
.target sm_72
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx75 = `
.version 8.4
.target sm_75
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx80 = `
.version 8.4
.target sm_80
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx86 = `
.version 8.4
.target sm_86
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx87 = `
.version 8.4
.target sm_87
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx89 = `
.version 8.4
.target sm_89
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
	shiftbytesyPtx90 = `
.version 8.4
.target sm_90
.address_size 64

	// .globl	shiftbytesy

.visible .entry shiftbytesy(
	.param .u64 shiftbytesy_param_0,
	.param .u64 shiftbytesy_param_1,
	.param .u32 shiftbytesy_param_2,
	.param .u32 shiftbytesy_param_3,
	.param .u32 shiftbytesy_param_4,
	.param .u32 shiftbytesy_param_5,
	.param .u8 shiftbytesy_param_6
)
{
	.reg .pred 	%p<9>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<9>;


	ld.param.u8 	%rs4, [shiftbytesy_param_6];
	ld.param.u64 	%rd1, [shiftbytesy_param_0];
	ld.param.u64 	%rd2, [shiftbytesy_param_1];
	ld.param.u32 	%r6, [shiftbytesy_param_2];
	ld.param.u32 	%r7, [shiftbytesy_param_3];
	ld.param.u32 	%r9, [shiftbytesy_param_4];
	ld.param.u32 	%r8, [shiftbytesy_param_5];
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %tid.x;
	mad.lo.s32 	%r1, %r11, %r10, %r12;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %tid.y;
	mad.lo.s32 	%r2, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.z;
	mov.u32 	%r17, %ctaid.z;
	mov.u32 	%r18, %tid.z;
	mad.lo.s32 	%r3, %r17, %r16, %r18;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	sub.s32 	%r4, %r2, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	setp.ge.s32 	%p7, %r4, %r7;
	or.pred  	%p8, %p6, %p7;
	mul.lo.s32 	%r5, %r3, %r7;
	@%p8 bra 	$L__BB0_3;

	add.s32 	%r19, %r4, %r5;
	mad.lo.s32 	%r20, %r19, %r6, %r1;
	cvt.s64.s32 	%rd3, %r20;
	cvta.to.global.u64 	%rd4, %rd2;
	add.s64 	%rd5, %rd4, %rd3;
	ld.global.nc.u8 	%rs4, [%rd5];

$L__BB0_3:
	add.s32 	%r21, %r5, %r2;
	mad.lo.s32 	%r22, %r21, %r6, %r1;
	cvt.s64.s32 	%rd6, %r22;
	cvta.to.global.u64 	%rd7, %rd1;
	add.s64 	%rd8, %rd7, %rd6;
	st.global.u8 	[%rd8], %rs4;

$L__BB0_4:
	ret;

}

`
)
