package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for shiftz kernel
var shiftzCode cu.Function

// Stores the arguments for shiftz kernel invocation
type shiftzArgsT struct {
	argDst    unsafe.Pointer
	argSrc    unsafe.Pointer
	argNx     int
	argNy     int
	argNz     int
	argShz    int
	argClampB float32
	argClampF float32
	argptr    [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shiftz kernel invocation
var shiftzArgs shiftzArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	shiftzArgs.argptr[0] = unsafe.Pointer(&shiftzArgs.argDst)
	shiftzArgs.argptr[1] = unsafe.Pointer(&shiftzArgs.argSrc)
	shiftzArgs.argptr[2] = unsafe.Pointer(&shiftzArgs.argNx)
	shiftzArgs.argptr[3] = unsafe.Pointer(&shiftzArgs.argNy)
	shiftzArgs.argptr[4] = unsafe.Pointer(&shiftzArgs.argNz)
	shiftzArgs.argptr[5] = unsafe.Pointer(&shiftzArgs.argShz)
	shiftzArgs.argptr[6] = unsafe.Pointer(&shiftzArgs.argClampB)
	shiftzArgs.argptr[7] = unsafe.Pointer(&shiftzArgs.argClampF)
}

// Wrapper for shiftz CUDA kernel, asynchronous.
func kShiftzAsync(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shz int, clampB float32, clampF float32, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("shiftz")
	}

	shiftzArgs.Lock()
	defer shiftzArgs.Unlock()

	if shiftzCode == 0 {
		shiftzCode = fatbinLoad(shiftzMap, "shiftz")
	}

	shiftzArgs.argDst = dst
	shiftzArgs.argSrc = src
	shiftzArgs.argNx = Nx
	shiftzArgs.argNy = Ny
	shiftzArgs.argNz = Nz
	shiftzArgs.argShz = shz
	shiftzArgs.argClampB = clampB
	shiftzArgs.argClampF = clampF

	args := shiftzArgs.argptr[:]
	cu.LaunchKernel(shiftzCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("shiftz")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_shiftz_async(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shz int, clampB float32, clampF float32, cfg *config) {
	kShiftzAsync(dst, src, Nx, Ny, Nz, shz, clampB, clampF, cfg)
}

// maps compute capability on PTX code for shiftz kernel.
var shiftzMap = map[int]string{
	0:  "",
	50: shiftzPtx50,
	52: shiftzPtx52,
	53: shiftzPtx53,
	60: shiftzPtx60,
	61: shiftzPtx61,
	62: shiftzPtx62,
	70: shiftzPtx70,
	72: shiftzPtx72,
	75: shiftzPtx75,
	80: shiftzPtx80,
	86: shiftzPtx86,
	87: shiftzPtx87,
	89: shiftzPtx89,
	90: shiftzPtx90,
}

// Backward-compatible map name used by the original fatbin registration.
var shiftz_map = shiftzMap

// shiftz PTX code for various compute capabilities.
const (
	shiftzPtx50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx72 = `
.version 8.4
.target sm_72
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx75 = `
.version 8.4
.target sm_75
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx80 = `
.version 8.4
.target sm_80
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx86 = `
.version 8.4
.target sm_86
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx87 = `
.version 8.4
.target sm_87
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx89 = `
.version 8.4
.target sm_89
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shiftzPtx90 = `
.version 8.4
.target sm_90
.address_size 64

	// .globl	shiftz

.visible .entry shiftz(
	.param .u64 shiftz_param_0,
	.param .u64 shiftz_param_1,
	.param .u32 shiftz_param_2,
	.param .u32 shiftz_param_3,
	.param .u32 shiftz_param_4,
	.param .u32 shiftz_param_5,
	.param .f32 shiftz_param_6,
	.param .f32 shiftz_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shiftz_param_0];
	ld.param.u64 	%rd2, [shiftz_param_1];
	ld.param.u32 	%r5, [shiftz_param_2];
	ld.param.u32 	%r6, [shiftz_param_3];
	ld.param.u32 	%r7, [shiftz_param_4];
	ld.param.u32 	%r8, [shiftz_param_5];
	ld.param.f32 	%f5, [shiftz_param_6];
	ld.param.f32 	%f4, [shiftz_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r3, %r8;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r7;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r4, %r6, %r2;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
)
