package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
)

// CUDA handle for zeromaskinv kernel
var zeromaskinvCode cu.Function

// Stores the arguments for zeromaskinv kernel invocation
type zeromaskinvArgsT struct {
	argDst     unsafe.Pointer
	argMaskLUT unsafe.Pointer
	argRegions unsafe.Pointer
	argN       int
	argptr     [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for zeromaskinv kernel invocation
var zeromaskinvArgs zeromaskinvArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	zeromaskinvArgs.argptr[0] = unsafe.Pointer(&zeromaskinvArgs.argDst)
	zeromaskinvArgs.argptr[1] = unsafe.Pointer(&zeromaskinvArgs.argMaskLUT)
	zeromaskinvArgs.argptr[2] = unsafe.Pointer(&zeromaskinvArgs.argRegions)
	zeromaskinvArgs.argptr[3] = unsafe.Pointer(&zeromaskinvArgs.argN)
}

// Wrapper for zeromaskinv CUDA kernel, asynchronous.
func kZeromaskinvAsync(dst unsafe.Pointer, maskLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("zeromaskinv")
	}

	zeromaskinvArgs.Lock()
	defer zeromaskinvArgs.Unlock()

	if zeromaskinvCode == 0 {
		zeromaskinvCode = fatbinLoad(zeromaskinvMap, "zeromaskinv")
	}

	zeromaskinvArgs.argDst = dst
	zeromaskinvArgs.argMaskLUT = maskLUT
	zeromaskinvArgs.argRegions = regions
	zeromaskinvArgs.argN = N

	args := zeromaskinvArgs.argptr[:]
	cu.LaunchKernel(zeromaskinvCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("zeromaskinv")
	}
}

// Backward-compatible wrapper for CUDA call sites that still use the
// historical snake_case name.
func k_zeromaskinv_async(dst unsafe.Pointer, maskLUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config) {
	kZeromaskinvAsync(dst, maskLUT, regions, N, cfg)
}

// maps compute capability on PTX code for zeromaskinv kernel.
var zeromaskinvMap = map[int]string{
	0:  "",
	50: zeromaskinvPtx50,
	52: zeromaskinvPtx52,
	53: zeromaskinvPtx53,
	60: zeromaskinvPtx60,
	61: zeromaskinvPtx61,
	62: zeromaskinvPtx62,
	70: zeromaskinvPtx70,
	72: zeromaskinvPtx72,
	75: zeromaskinvPtx75,
	80: zeromaskinvPtx80,
	86: zeromaskinvPtx86,
	87: zeromaskinvPtx87,
	89: zeromaskinvPtx89,
	90: zeromaskinvPtx90,
}

// Backward-compatible map name used by the original fatbin registration.
var zeromaskinv_map = zeromaskinvMap

// zeromaskinv PTX code for various compute capabilities.
const (
	zeromaskinvPtx50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx72 = `
.version 8.4
.target sm_72
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx75 = `
.version 8.4
.target sm_75
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx80 = `
.version 8.4
.target sm_80
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx86 = `
.version 8.4
.target sm_86
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx87 = `
.version 8.4
.target sm_87
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx89 = `
.version 8.4
.target sm_89
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
	zeromaskinvPtx90 = `
.version 8.4
.target sm_90
.address_size 64

	// .globl	zeromaskinv

.visible .entry zeromaskinv(
	.param .u64 zeromaskinv_param_0,
	.param .u64 zeromaskinv_param_1,
	.param .u64 zeromaskinv_param_2,
	.param .u32 zeromaskinv_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd2, [zeromaskinv_param_0];
	ld.param.u64 	%rd3, [zeromaskinv_param_1];
	ld.param.u64 	%rd4, [zeromaskinv_param_2];
	ld.param.u32 	%r2, [zeromaskinv_param_3];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd5, %rd4;
	cvt.s64.s32 	%rd1, %r1;
	add.s64 	%rd6, %rd5, %rd1;
	ld.global.nc.u8 	%rs1, [%rd6];
	cvta.to.global.u64 	%rd7, %rd3;
	cvt.u32.u16 	%r9, %rs1;
	and.b32  	%r10, %r9, 255;
	mul.wide.u32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	setp.neu.f32 	%p2, %f1, 0f00000000;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd10, %rd2;
	shl.b64 	%rd11, %rd1, 2;
	add.s64 	%rd12, %rd10, %rd11;
	mov.u32 	%r11, 0;
	st.global.u32 	[%rd12], %r11;

$L__BB0_3:
	ret;

}

`
)
